### ISSUE TITLE
Failing to find primary server in config

### ISSUE THREAD

**Issue by Sperryfreak01** [Sperryfreak01/RadarrSync#23]
**Describe the bug**
Not finding the Primary Server in the config file [source](https://www.reddit.com/r/radarr/comments/9ek2lp/radarrsync_v12_beta_release/e5qjyy0/)

**To Reproduce**
Hi there - just grabbed this and ran into an issue running it. Installed per the instructions, made sure all my prerequisites were in, and edited the Config file...The Radarr section is definitely there (didn't touch the headers in the config file).....thoughts?

**Expected behavior**
Not crash 

**Configuration**
N/A

**Logs**
```
feez@dh-download:~/RadarrSync-1.2$ python3 ./RadarrSync.py
Traceback (most recent call last):
File "./RadarrSync.py", line 213, in <module>
radarrServer['url'] = ConfigSectionMap("Radarr")['url']
File "./RadarrSync.py", line 19, in ConfigSectionMap
options = Config.options(section)
File "/usr/lib/python3.6/configparser.py", line 675, in options
raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Radarr'
```

**Comment by dxbluke** [comment]
Hi, this is still an issue in my setup using docker. Has there been any progress? Thanks
