### ISSUE TITLE
Unable to run RadarrSync configparser.NoSectionError: No section: 'Radarr'

### ISSUE THREAD

**Issue by akizzle** [Sperryfreak01/RadarrSync#28]
**Describe the bug**
Receiving the below when running RadarrSync.py
  File "RadarrSync/RadarrSync.py", line 51, in <module>
    radarr_url = ConfigSectionMap("Radarr")['url']
  File "RadarrSync/RadarrSync.py", line 29, in ConfigSectionMap
    options = Config.options(section)
  File "/usr/lib/python3.5/configparser.py", line 674, in options
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Radarr'

**To Reproduce**
Running: python3 RadarrSync/RadarrSync.py

**Expected behavior**

**Configuration**
Please attach your configuration file (Config.txt), remember to remove any personal information (api key especially if your radarr install is accessible from the web)
[Radarr]
url = http://10.25.10.4:7878
key = APIKEY

[Radarr4K]
url = http://10.25.10.4:7879
key = APIKEY
profile = 1080P-UHD-REMUX-AA

**Logs**
Please include a log of the issue happening.  Delete the Output.txt file, run RadarrSync and attache the new Output.txt file.

Don't see an Output.txt file in the directory.

**Comment by akizzle** [comment]
Ran the command from the folder and was able to get a bit further.

2018-10-12 21:34:57,851 [MainThread  ] [INFO ]  Starting new HTTP connection (1): 10.25.10.4
2018-10-12 21:34:59,751 [MainThread  ] [INFO ]  Starting new HTTP connection (1): 10.25.10.4
Traceback (most recent call last):
  File "RadarrSync.py", line 89, in <module>
    if movie['profileId'] == int(ConfigSectionMap(server)['profile']):
ValueError: invalid literal for int() with base 10: '1080P-UHD-REMUX-AA'
