### ISSUE TITLE
Script Errors Out

### ISSUE THREAD

**Issue by ysg23** [Sperryfreak01/RadarrSync#37]
**Describe the bug**
Can't run the script

**To Reproduce**
Edited the file, input my own radarr links, APIs and profiles

**Expected behavior**
When I run Config.txt, I get the following

Traceback (most recent call last):
File "RadarrSync.py", line 239, in
syncServer['url'] = ConfigSectionMap(syncServer['name'])['url']
KeyError: 'url'

However if I rename to DevConfig.txt, I get the following

Traceback (most recent call last):

File "RadarrSync.py", line 51, in <module>

radarr_url = ConfigSectionMap("Radarr")['url']

File "RadarrSync.py", line 29, in ConfigSectionMap

options = Config.options(section)

File "/usr/lib/python3.6/configparser.py", line 675, in options

raise NoSectionError(section) from None

configparser.NoSectionError: No section: 'Radarr'

**Configuration**
[General]

[Radarr]
url = https://radarr.mydomain.ca
profile = HD

[Radarr4k]
url = https://radarr4k.mydomain.ca
destination_profile = UltraHD

**Logs**
Output.txt is empty if I run DevConfig.txt or run it as Config.txt

**Comment by cdarais** [comment]
I too have this issue. Did you ever find a solution?

**Comment by BigBenM** [comment]
the profile needs to be an ID (numeric) not the name of the profile

**Comment by Jovetic** [comment]
That was not your issue.  It would have been, the script was unable to find the config file [Radarr] section.  I edited the script to this: LINE48

From:     settingsFilename = os.path.join(os.getcwd(), 'Config.txt')

To:          settingsFilename = 'C:\Automation\RadarrSync-master\Config.txt'

The join was not working, possibly a windows thing. Just pop in your path to the config file. Posting this to save someone else running around looking for the wrong thing.

**Comment by ysg23** [comment]
Okay so I am retrying now .. running on Linux so I changed settingsFilename = 'Config.txt'

Unfortunately, now I get this error:
python RadarrSync.py
Traceback (most recent call last):
  File "RadarrSync.py", line 5, in <module>
    import configparser
ImportError: No module named configparser

If I change to import ConfigParser, I get this
python RadarrSync.py
Traceback (most recent call last):
  File "RadarrSync.py", line 41, in <module>
    Config = configparser.ConfigParser()
NameError: name 'configparser' is not defined

If I change it to Config = ConfigParser, I get this:
 python RadarrSync.py
Traceback (most recent call last):
  File "RadarrSync.py", line 49, in <module>
    Config.read(settingsFilename)
AttributeError: 'module' object has no attribute 'read'

**Comment by mradzkii** [comment]
getting this issue too
